import About from "@/components/index/About";
import Carousel from "@/components/index/Carousel";
import Products from "@/components/index/Products";
import Welcome from "@/components/index/Welcome";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ujwal Dairy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Carousel />
      <Welcome />
      <Products />
      <About />
    </>
  );
}
